name: Build and Run CodeCov
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write #  to cancel/stop running workflows (styfle/cancel-workflow-action)
  contents: read #  to fetch code (actions/checkout)

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        node: [20]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        working-directory: ./front
        run: yarn ci

      - name: ▶️ Run build
        working-directory: ./front
        run: yarn build

      # - name: ▶️ Run test
      #   working-directory: ./front
      #   run: yarn vitest run --coverage

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ./front/coverage
