name: EC2에 배포하기

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH 연결 단계
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$EC2_SSH_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: 빌드후 배포 단계
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
            set -x
            cd ~/coreal_repo
            git pull origin develop
            cd front
            echo "Installing dependencies"
            yarn install
            echo "Building project"
            yarn build
            echo "PM2 프로세스 상태 확인"
            pm2 list
            if pm2 list | grep -q "coreal_frontend"; then
              echo "기존 프로세스 중지 및 삭제"
              pm2 stop coreal_frontend
              pm2 delete coreal_frontend
            fi
            echo "새 프로세스 시작"
            pm2 start yarn --name "coreal_frontend" -- start --port 8080
            echo "프론트엔드 배포 완료."
          '

      - name: 배포상태 확인
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
            pm2 list
            echo "배포성공."
          '